import { Listing, Agent, Inquiry } from "./types";

export const seedAgents: Agent[] = [
  {
    id: "agent-1",
    name: "Chinedu Okafor",
    role: "agent",
    email: "agent@plinth.ng",
    phone: "+2348021234567",
    whatsapp: "2348021234567",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    bio: "Licensed real estate agent with 8 years experience in Lagos property market. Specializing in residential rentals across Lekki and Victoria Island.",
    verified: true,
    joinedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "agent-2",
    name: "Adewale Adeyemi",
    role: "agent",
    email: "adewale@example.com",
    phone: "+2348039876543",
    whatsapp: "2348039876543",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
    bio: "Property consultant focused on Ikeja and Yaba. Helping clients find their perfect homes in mainland Lagos.",
    verified: false,
    joinedAt: "2024-03-20T00:00:00Z",
  },
  {
    id: "agent-3",
    name: "Ngozi Eze",
    role: "agent",
    email: "ngozi@example.com",
    phone: "+2348123456789",
    whatsapp: "2348123456789",
    photo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face",
    bio: "Real estate professional serving Ajah and Surulere areas. Committed to transparent dealings and client satisfaction.",
    verified: true,
    joinedAt: "2024-02-10T00:00:00Z",
  },
];

export const seedListings: Listing[] = [
  {
    id: "listing-1",
    title: "Modern 3-Bedroom Apartment in Lekki Phase 1",
    purpose: "rent",
    category: "apartment",
    bedrooms: 3,
    bathrooms: 2,
    priceNGN: 2500000,
    priceUnit: "year",
    area: "Lekki Phase 1",
    lga: "Eti-Osa",
    state: "Lagos",
    description: "Spacious 3-bedroom apartment in a secure estate with 24/7 security, constant water supply, and backup power. Features modern kitchen, fitted wardrobes, and balcony. Close to malls and schools.",
    amenities: ["24/7 Security", "Constant Water", "Backup Power", "Fitted Kitchen", "Balcony", "Parking"],
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
    ],
    agentId: "agent-1",
    status: "available",
    featured: true,
    views: 142,
    createdAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "listing-2",
    title: "Luxury 4-Bedroom Duplex in Victoria Island",
    purpose: "rent",
    category: "duplex",
    bedrooms: 4,
    bathrooms: 4,
    priceNGN: 8000000,
    priceUnit: "year",
    area: "Victoria Island",
    lga: "Eti-Osa",
    state: "Lagos",
    description: "Executive 4-bedroom duplex with BQ, swimming pool, and gym access. Premium finishes throughout, smart home features, and panoramic city views. Ideal for expatriates.",
    amenities: ["Swimming Pool", "Gym", "BQ", "Smart Home", "Panoramic Views", "Security"],
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
    ],
    agentId: "agent-1",
    status: "available",
    featured: true,
    views: 287,
    createdAt: "2024-05-28T00:00:00Z",
  },
  {
    id: "listing-3",
    title: "Cozy 2-Bedroom Flat in Yaba",
    purpose: "rent",
    category: "apartment",
    bedrooms: 2,
    bathrooms: 1,
    priceNGN: 800000,
    priceUnit: "year",
    area: "Yaba",
    lga: "Lagos Mainland",
    state: "Lagos",
    description: "Well-maintained 2-bedroom flat in a quiet neighborhood. Close to UNILAG and teaching hospital. Good road network and accessible public transport.",
    amenities: ["Parking", "Good Roads", "Near UNILAG", "Water Supply"],
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
    ],
    agentId: "agent-2",
    status: "available",
    featured: false,
    views: 89,
    createdAt: "2024-06-05T00:00:00Z",
  },
  {
    id: "listing-4",
    title: "3-Bedroom Bungalow in Ikeja GRA",
    purpose: "rent",
    category: "bungalow",
    bedrooms: 3,
    bathrooms: 2,
    priceNGN: 3500000,
    priceUnit: "year",
    area: "Ikeja GRA",
    lga: "Ikeja",
    state: "Lagos",
    description: "Detached 3-bedroom bungalow in prestigious GRA. Large compound, garden, and ample parking space. Family-friendly neighborhood with good schools nearby.",
    amenities: ["Garden", "Ample Parking", "Security", "Near Schools", "Water Supply"],
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    ],
    agentId: "agent-2",
    status: "available",
    featured: true,
    views: 156,
    createdAt: "2024-05-20T00:00:00Z",
  },
  {
    id: "listing-5",
    title: "Self-Contain Studio in Surulere",
    purpose: "rent",
    category: "self-contain",
    bedrooms: 1,
    bathrooms: 1,
    priceNGN: 400000,
    priceUnit: "year",
    area: "Surulere",
    lga: "Surulere",
    state: "Lagos",
    description: "Compact self-contain studio perfect for young professionals. Tiled floors, modern bathroom, and kitchenette. Close to National Stadium and good transport links.",
    amenities: ["Kitchenette", "Tiled Floors", "Near Stadium", "Transport Links"],
    images: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop",
    ],
    agentId: "agent-3",
    status: "available",
    featured: false,
    views: 67,
    createdAt: "2024-06-10T00:00:00Z",
  },
  {
    id: "listing-6",
    title: "4-Bedroom Terrace Duplex in Ajah",
    purpose: "rent",
    category: "duplex",
    bedrooms: 4,
    bathrooms: 3,
    priceNGN: 1800000,
    priceUnit: "year",
    area: "Ajah",
    lga: "Eti-Osa",
    state: "Lagos",
    description: "Modern terrace duplex in developing Ajah area. Spacious rooms, good ventilation, and estate security. Close to Lekki-Epe expressway.",
    amenities: ["Estate Security", "Good Ventilation", "Near Expressway", "Parking"],
    images: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
    ],
    agentId: "agent-3",
    status: "available",
    featured: true,
    views: 203,
    createdAt: "2024-05-15T00:00:00Z",
  },
  {
    id: "listing-7",
    title: "Commercial Office Space in Victoria Island",
    purpose: "rent",
    category: "office",
    bedrooms: 0,
    bathrooms: 2,
    priceNGN: 5000000,
    priceUnit: "year",
    area: "Victoria Island",
    lga: "Eti-Osa",
    state: "Lagos",
    description: "500sqm open plan office space in prime VI location. Central AC, elevator access, and backup generator. Suitable for corporate headquarters.",
    amenities: ["Central AC", "Elevator", "Backup Generator", "Security", "Parking"],
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop",
    ],
    agentId: "agent-1",
    status: "available",
    featured: false,
    views: 45,
    createdAt: "2024-06-08T00:00:00Z",
  },
  {
    id: "listing-8",
    title: "2-Bedroom Shortlet in Lekki",
    purpose: "shortlet",
    category: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    priceNGN: 150000,
    priceUnit: "month",
    area: "Lekki Phase 1",
    lga: "Eti-Osa",
    state: "Lagos",
    description: "Fully furnished 2-bedroom apartment for short stays. Netflix, WiFi, cleaning service included. Perfect for business travelers or tourists.",
    amenities: ["Furnished", "WiFi", "Netflix", "Cleaning Service", "Generator"],
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop",
    ],
    agentId: "agent-1",
    status: "available",
    featured: true,
    views: 312,
    createdAt: "2024-06-12T00:00:00Z",
  },
  {
    id: "listing-9",
    title: "Shop Space in Ikeja",
    purpose: "rent",
    category: "shop",
    bedrooms: 0,
    bathrooms: 1,
    priceNGN: 600000,
    priceUnit: "year",
    area: "Ikeja",
    lga: "Ikeja",
    state: "Lagos",
    description: "Ground floor shop space in busy commercial area. High foot traffic, good for retail. Glass frontage and secure shutters.",
    amenities: ["High Foot Traffic", "Glass Frontage", "Security", "Parking"],
    images: [
      "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800&h=600&fit=crop",
    ],
    agentId: "agent-2",
    status: "available",
    featured: false,
    views: 38,
    createdAt: "2024-06-03T00:00:00Z",
  },
  {
    id: "listing-10",
    title: "Land for Sale in Lekki",
    purpose: "sale",
    category: "land",
    bedrooms: 0,
    bathrooms: 0,
    priceNGN: 45000000,
    priceUnit: "total",
    area: "Lekki Scheme 2",
    lga: "Eti-Osa",
    state: "Lagos",
    description: "600sqm plot in fast-developing Lekki Scheme 2. Dry land, good title documents. Close to proposed road network.",
    amenities: ["Dry Land", "Good Title", "Near Road Network"],
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop",
    ],
    agentId: "agent-1",
    status: "available",
    featured: false,
    views: 78,
    createdAt: "2024-05-25T00:00:00Z",
  },
  {
    id: "listing-11",
    title: "3-Bedroom Apartment in Ikoyi",
    purpose: "rent",
    category: "apartment",
    bedrooms: 3,
    bathrooms: 2,
    priceNGN: 4500000,
    priceUnit: "year",
    area: "Ikoyi",
    lga: "Eti-Osa",
    state: "Lagos",
    description: "Elegant 3-bedroom apartment in exclusive Ikoyi. Waterfront views, premium finishes, and concierge service. Access to communal gym and pool.",
    amenities: ["Waterfront Views", "Concierge", "Gym", "Pool", "Security"],
    images: [
      "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop",
    ],
    agentId: "agent-1",
    status: "pending",
    featured: false,
    views: 0,
    createdAt: "2024-06-15T00:00:00Z",
  },
  {
    id: "listing-12",
    title: "2-Bedroom Flat in Maryland",
    purpose: "rent",
    category: "apartment",
    bedrooms: 2,
    bathrooms: 1,
    priceNGN: 900000,
    priceUnit: "year",
    area: "Maryland",
    lga: "Ikeja",
    state: "Lagos",
    description: "Spacious 2-bedroom flat in serene Maryland environment. Good road network, close to airport. Well-maintained building with elevator.",
    amenities: ["Elevator", "Near Airport", "Water Supply", "Parking"],
    images: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
    ],
    agentId: "agent-2",
    status: "available",
    featured: false,
    views: 54,
    createdAt: "2024-06-07T00:00:00Z",
  },
  {
    id: "listing-13",
    title: "4-Bedroom Duplex in Magodo",
    purpose: "rent",
    category: "duplex",
    bedrooms: 4,
    bathrooms: 4,
    priceNGN: 2800000,
    priceUnit: "year",
    area: "Magodo",
    lga: "Ikeja",
    state: "Lagos",
    description: "Spacious 4-bedroom duplex in secure Magodo estate. BQ, garden, and 24/7 security. Family-friendly with good schools nearby.",
    amenities: ["BQ", "Garden", "24/7 Security", "Near Schools", "Water Supply"],
    images: [
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
    ],
    agentId: "agent-2",
    status: "rented",
    featured: false,
    views: 198,
    createdAt: "2024-04-20T00:00:00Z",
  },
  {
    id: "listing-14",
    title: "Studio Apartment in Obalende",
    purpose: "rent",
    category: "self-contain",
    bedrooms: 1,
    bathrooms: 1,
    priceNGN: 450000,
    priceUnit: "year",
    area: "Obalende",
    lga: "Lagos Island",
    state: "Lagos",
    description: "Compact studio apartment in central Obalende. Walking distance to CMS and major bus stops. Good for young professionals.",
    amenities: ["Central Location", "Near Transport", "Water Supply"],
    images: [
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&h=600&fit=crop",
    ],
    agentId: "agent-3",
    status: "available",
    featured: false,
    views: 91,
    createdAt: "2024-06-02T00:00:00Z",
  },
];

export const seedInquiries: Inquiry[] = [
  {
    id: "inquiry-1",
    listingId: "listing-1",
    agentId: "agent-1",
    name: "Tunde Bakare",
    phone: "+2348055555555",
    message: "I'm interested in the Lekki Phase 1 apartment. Is it still available for viewing?",
    channel: "form",
    status: "new",
    createdAt: "2024-06-14T10:30:00Z",
  },
  {
    id: "inquiry-2",
    listingId: "listing-2",
    agentId: "agent-1",
    name: "Sarah Johnson",
    phone: "+2348066666666",
    message: "Hello, I'd like to schedule a viewing of the Victoria Island duplex.",
    channel: "whatsapp",
    status: "contacted",
    createdAt: "2024-06-13T15:45:00Z",
  },
  {
    id: "inquiry-3",
    listingId: "listing-3",
    agentId: "agent-2",
    name: "Emeka Nwosu",
    phone: "+2348077777777",
    message: "Please send more details about the Yaba flat. Is the rent negotiable?",
    channel: "form",
    status: "new",
    createdAt: "2024-06-14T08:20:00Z",
  },
  {
    id: "inquiry-4",
    listingId: "listing-6",
    agentId: "agent-3",
    name: "Fatima Ibrahim",
    phone: "+2348088888888",
    message: "I'm interested in the Ajah duplex. Can I see it this weekend?",
    channel: "whatsapp",
    status: "contacted",
    createdAt: "2024-06-12T12:00:00Z",
  },
  {
    id: "inquiry-5",
    listingId: "listing-8",
    agentId: "agent-1",
    name: "John Doe",
    phone: "+2348099999999",
    message: "Need the shortlet for 2 weeks in July. What's the availability?",
    channel: "form",
    status: "closed",
    createdAt: "2024-06-10T14:30:00Z",
  },
  {
    id: "inquiry-6",
    listingId: "listing-4",
    agentId: "agent-2",
    name: "Amina Yusuf",
    phone: "+2348100000000",
    message: "Is the Ikeja GRA bungalow still available? I have a family of 5.",
    channel: "whatsapp",
    status: "new",
    createdAt: "2024-06-14T09:15:00Z",
  },
  {
    id: "inquiry-7",
    listingId: "listing-5",
    agentId: "agent-3",
    name: "Chinedu Okoro",
    phone: "+2348111111111",
    message: "Looking for a studio in Surulere. Is this available immediately?",
    channel: "form",
    status: "contacted",
    createdAt: "2024-06-11T16:45:00Z",
  },
  {
    id: "inquiry-8",
    listingId: "listing-1",
    agentId: "agent-1",
    name: "Grace Adebayo",
    phone: "+2348122222222",
    message: "What's the service charge for the Lekki apartment?",
    channel: "whatsapp",
    status: "new",
    createdAt: "2024-06-14T11:00:00Z",
  },
];
